Check that moderation channelID is valid before attempting profanity check
Knights-Of-Academia/horace pull request #210
Opened 2021-01-17 19:44 UTC by catalinp86

If there is a configuration error is present it's not logged to console. 

This validates that channel ID for `moderation` is valid before any attempt to check for profanities. If the ID is invalid it will be logged to console and it will be easy to detect.

2021-01-17 19:50 UTC, ThatNerdSquared requested changes

2021-01-17 19:50 UTC, ThatNerdSquared commented on eventActions/profanityActions.js
> +			console.log("Error! Moderation Channel ID in Config in likely invalid. Please verify!");
Small nitpick: single quotes :)

2021-01-17 21:15 UTC, KO4JZT approved these changes

2021-01-19 22:41 UTC, catalinp86 commented on eventActions/profanityActions.js
> +			console.log("Error! Moderation Channel ID in Config in likely invalid. Please verify!");
Thanks! Solved it!

2021-01-19 22:47 UTC, ThatNerdSquared approved these changes

2021-01-19 22:48 UTC, merged