Added article command
Knights-Of-Academia/horace pull request #235
Opened 2021-04-21 06:08 UTC by mukkuzzz

Added article Command

2021-04-21 07:15 UTC, debashisbiswas commented
Thanks for your changes! Before these get merged, we're double-checking to clarify the intended behavior of the command. We might need it to link to the most recent article, rather than all of the articles, so I'll let you know when I hear back on this.

2021-04-21 07:21 UTC, debashisbiswas commented
Until then, would you be able to fix the indentation/whitespace/spacing/missing newline in `article.test.js`? Should be a quick fix.

2021-04-21 08:16 UTC, mukkuzzz commented
> Until then, would you be able to fix the indentation/whitespace/spacing/missing newline in `article.test.js`? Should be a quick fix.

DONE

2021-04-21 08:28 UTC, mukkuzzz commented
@debashisbiswas hey u can review this now??

2021-04-21 18:54 UTC, debashisbiswas commented
Still waiting to hear back about the indented behavior.

2021-04-22 07:25 UTC, debashisbiswas requested changes
Sorry for all the comments! Most of them are requests for changes to some of the strings for grammar and capitalization, and you can read the comments for details on the other requested changes.

2021-04-22 07:25 UTC, debashisbiswas commented on .gitignore
> +out.txt
Would you be able to remove this change? This doesn't need to get merged.

2021-04-22 07:25 UTC, debashisbiswas commented on commands/article.js
> +const random = require('random');
I don't think we need to add another dependency for this, can you implement this with `Math.random()` instead?

2021-04-22 07:25 UTC, debashisbiswas commented on commands/article.js
> +	let response = `Here is a article i found called "${(feed.items[r].title)}" here is the link to it ${feed.items[r].link}`;
It's not necessarily clear to the user that this article was randomly selected. How about something like:
`Here's a random article from KOA titled "${(feed.items[r].title)}": ${feed.items[r].link}`

2021-04-22 07:25 UTC, debashisbiswas commented on commands/article.js
> +			response = "This is home page of the articles https://kingsofacademacia.org/category/articles";
This is not the correct link to the website. Use `https://knightsofacademia.org/category/articles`

Also, grammar - how about something like this for consistency with other commands?
`KOA Article Archive: https://knightsofacademia.org/category/articles`

2021-04-22 07:25 UTC, debashisbiswas commented on commands/article.js
> +			response = `Here is the latest article i found called "${(feed.items[0].title)}" here is the link to it ${feed.items[0].link}`
Capitalization/grammar, how about this:
`The latest newsletter from KOA is called "${(feed.items[0].title)}" and can be found here: ${feed.items[0].link}.`

2021-04-22 07:25 UTC, debashisbiswas commented on package.json
> +    "random": "^3.0.5",
See above comment about unnecessary dependency

2021-04-22 07:58 UTC, mukkuzzz commented
OK i will change them

2021-04-22 14:38 UTC, mukkuzzz commented
@debashisbiswas Changes done

2021-04-22 17:15 UTC, debashisbiswas approved these changes
Great, thanks for all the changes. Looks great!

2021-04-22 17:16 UTC, merged

2021-04-22 17:19 UTC, mukkuzzz commented
> Great, thanks for all the changes. Looks great!

Thanks.