Add a !choose (alias !pick) command
Knights-Of-Academia/horace pull request #31
Opened 2019-10-10 20:54 UTC by ziebam

As mentioned in the commit message, the parsing is somewhat hacky, but I didn't know how to solve that better. Regular splitting wouldn't work as then the whitespace was removed. I'm open for suggestions on how I might improve it!

2019-10-11 05:56 UTC, Tekrus requested changes
Thanks for your contribution! Here's some feedback on how you can improve it a little as you wished for. 👋

2019-10-11 05:56 UTC, Moesgaarda commented on commands/choose.js
> +	}
Is this needed? Which type does args have before converting them? (Hint, you can use [typeOf](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/typeof) to check this)

2019-10-11 05:56 UTC, Moesgaarda commented on commands/choose.test.js
> +});
Does test the full functionality of the command? Can it ever pick the second or possibly object? What about using choose with no args?

2019-10-11 16:12 UTC, ziebam commented
I've done what I can, although I'm still open to feedback! I'm mostly not sure if the regex parsing is correct there or if I should seek a better way.

2019-10-12 11:18 UTC, Dendrobyte approved these changes
!choose Approve,Comment,Request Changes

Horace says... Approve!

2019-10-12 12:06 UTC, erik-ahlburg-schmidt approved these changes

2019-10-12 12:07 UTC, Tekrus approved these changes

2019-10-12 12:07 UTC, Moesgaarda commented
Triple approved!

2019-10-12 12:07 UTC, merged